vim.cmd("hi default link DapUIVariable Normal")
vim.cmd("hi default DapUIScope guifg=#A9FF68")
vim.cmd("hi default DapUIType guifg=#D484FF")
vim.cmd("hi default DapUIDecoration guifg=#00F1F5")
vim.cmd("hi default DapUIThread guifg=#A9FF68")
vim.cmd("hi default DapUIStoppedThread guifg=#F70067 gui=bold")
vim.cmd("hi default link DapUIFrameName Normal")
vim.cmd("hi default DapUIFrameSource guifg=#D484FF")
vim.cmd("hi default DapUILineNumber guifg=#00f1f5")
vim.cmd("hi default DapUIFloatBorder guifg=#00F1F5")
vim.cmd("hi default DapUIWatchesHeader guifg=#A9FF68")
vim.cmd("hi default DapUIWatchesEmpty guifg=#F70067")
vim.cmd("hi default DapUIWatchesValue guifg=#D484FF")
